name: Run tests

on:
  push:
    branches:
      - solution_v2
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: PYTHONPATH=. pytest

      - name: Build Docker image
        run: docker build -t prime_pack .

      - name: Tag Docker image
        run: docker tag prime_pack abekeabeke/prime_pack

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker push abekeabeke/prime_pack